### PR TITLE
Added 'shallow' class to change height of hero from 600px to 500px

### PR DESCRIPTION
**Pull request by byu-ecen**

### CODE REVIEW

**Comment by kebowdog** [comment]
@byu-ecen Thanks for submitting a PR on this project! While your changes technically work, they're also not strictly necessary. The 600px height is just a default - you can change the height to whatever you want using regular css (i.e. by adding style="height: 500px" to the <byu-hero-banner> tag. Can you try that and confirm it works for you? If so I'll close the PR.

**Comment by byu-ecen** [comment]
@kebowdog Hey, thanks for the feedback. While adding that style tag would solve the problem for some formats of the hero display, it won't properly adjust the transparent background on the transparent-overlay class. The height and upper margin of this transparent box need to be adjusted along with the height of the container itself. An example can be seen at https://ece.byu.edu/department. Please let me know if there's any confusion I can clear up.

**Comment by kebowdog** [comment]
I see what you mean - good catch. Can you give me a day to see if we can do this with percent-based styles so we can accommodate any height? If that doesn't work I'll go ahead and merge and release.

**Comment by michaelpratt28** [comment]
PR #15 fixes this.

**Comment by kebowdog** [comment]
I've released version 1.2.3 which includes PR #15 and confirmed that it works on https://ece.byu.edu/department. The default will continue to be 600px, but you should now be able to set any height you want for the banner using standard css.

**Pull request closed without merging**
